// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf1lPJWAbH4tVWOPojB8WYxrcYJhbt6q4',
    appId: '1:459173720756:web:ee5eb7e54a332734165de1',
    messagingSenderId: '459173720756',
    projectId: 'ecommerceapp-7d076',
    authDomain: 'ecommerceapp-7d076.firebaseapp.com',
    storageBucket: 'ecommerceapp-7d076.firebasestorage.app',
    measurementId: 'G-5R91BZDGJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArghEclGg2z1c63M5rahh-fO8pnmUzSSM',
    appId: '1:459173720756:android:a9a793f7d50d0f2e165de1',
    messagingSenderId: '459173720756',
    projectId: 'ecommerceapp-7d076',
    storageBucket: 'ecommerceapp-7d076.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6EpbGDDXPlgT4C0-_n3iBDnxubHYf9uY',
    appId: '1:459173720756:ios:b60296f52f812b79165de1',
    messagingSenderId: '459173720756',
    projectId: 'ecommerceapp-7d076',
    storageBucket: 'ecommerceapp-7d076.firebasestorage.app',
    iosBundleId: 'com.ecommerce.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6EpbGDDXPlgT4C0-_n3iBDnxubHYf9uY',
    appId: '1:459173720756:ios:b60296f52f812b79165de1',
    messagingSenderId: '459173720756',
    projectId: 'ecommerceapp-7d076',
    storageBucket: 'ecommerceapp-7d076.firebasestorage.app',
    iosBundleId: 'com.ecommerce.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf1lPJWAbH4tVWOPojB8WYxrcYJhbt6q4',
    appId: '1:459173720756:web:7a5fe7b63100eba9165de1',
    messagingSenderId: '459173720756',
    projectId: 'ecommerceapp-7d076',
    authDomain: 'ecommerceapp-7d076.firebaseapp.com',
    storageBucket: 'ecommerceapp-7d076.firebasestorage.app',
    measurementId: 'G-JENJHDM1BK',
  );
}
